config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>トレタ用語検定</title>
  <%= stylesheet_link_tag 'bootstrap' %>
  <%= stylesheet_link_tag 'freelancer' %>
  <%= stylesheet_link_tag 'green' %>
  <%= stylesheet_link_tag 'red' %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: white;">

<%= yield %>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container" style="color: #777;">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">トレタ用語集</a>
            </div>
        </div>
        <!-- /.container-fluid -->
    </nav>
    <div class="content-wrapper" style="margin-top:120px; background-color: white;">
      <div class="row">
        <div class="col-lg-2 col-md-1">
        </div>
        <div class="col-lg-8 col-md-10" id="questionList">
          <h1 style="color: #8ACD35; text-align: center;">トレタ用語検定</h1>
          <h2 style="text-align: center; color: #777;">満点目指して頑張ろう！</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-2"></div>
        <div class="col-lg-4 col-md-8" id="answerCheck" style="margin: 0 20px;">
          <button style="margin:30px auto;" class="btn btn-warning btn-lg btn-block">アンサーチェック！</button>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-2 col-md-1"></div>
        <div class="col-lg-8 col-md-10" id="showScore" style="text-align: center; color: #777;">
        </div>
      </div>
    </div>
      <%= javascript_include_tag 'jquery' %>
      <%= javascript_include_tag 'bootstrap.min' %>
      <%= javascript_include_tag 'custom.min' %>
      <%= javascript_include_tag 'icheck' %>
    <script>

    $(function() {
      //問題リスト
      var questions = [
        {
          ansDescription: "オリーブオイルにニンニクを加え、風味が全体に行き渡るように弱火で加熱したオイルソース",
          misDiscription: "オリーブオイルにトウガラシを漬けた、料理に辛味を加えるオイルソース",
          ansWord: "アーリオ・オーリオ",
          misAnsWord: "アーリオ・ピカンテ",
          explanation: "「aglio」はニンニク、「olio」は油の意味。オリーブオイルにニンニクを加え、風味が全体に行き渡るように弱火で加熱したオイルソースのこと。パスタ料理などに用いられる。"
        },
        {
          ansDescription: "フランス語で一品料理",
          misDiscription: "フランス語でコース料理",
          ansWord: "アラカルト",
          misAnsWord: "ターブルドート",
          explanation: "レストランなどで、あらかじめ組んであるセットやコースメニューに対し、食事客がメニューブックの中から好みに応じて1品ずつ選べる一品料理のこと。フランス語"
        }
      ];

      //シャッフル部分
      function shuffle(array) {
        var n = array.length, t, i;

        while (n) {
          i = Math.floor(Math.random() * n--);
          t = array[n];
          array[n] = array[i];
          array[i] = t;
        }

        return array;
      }

      //問題用DOM生成
      var randomQuestions = shuffle(questions);
      var questionNum = 1;
      while(randomQuestions.length > 0 || questionNum > 20){
        var rnd1 = Math.floor( Math.random() * 2 );
        var questionText = "";
        if(rnd1 == 0){
          questionText = randomQuestions[0].ansDescription + "は？";
        }else{
          questionText = randomQuestions[0].ansWord + "とは？";
        }
        var htmlText =  '<div class="row" style="margin: 0;"><div class="col-md-12"><h3 style="color: #777;">第' +
        questionNum + '問．' + questionText + '</h3></div>';

        var rnd2 = Math.floor( Math.random() * 2 );

        if(rnd1 == 0){

          var ansWordHtmlText = '<div class="col-md-6"><input type="radio" name="'+ questionNum +'" id="ans-' + questionNum +'" /><label>'+ randomQuestions[0].ansWord + '</label></div>';
          var misAnsWordHtmlText = '<div class="col-md-6"><input type="radio" name="'+ questionNum +'"/><label>' + randomQuestions[0].misAnsWord + '</label></div>';

          if(rnd2 == 0){
            htmlText += ansWordHtmlText;
            htmlText += misAnsWordHtmlText;
          }else{
            htmlText += misAnsWordHtmlText;
            htmlText += ansWordHtmlText;
          }
        }else{

          var ansDescriptionHtmlText = '<div class="col-md-6"><input type="radio" name="'+ questionNum +'" id="ans-' + questionNum +
          '" /><label>'+ randomQuestions[0].ansDescription + '</label></div>';
          var misDiscriptionHtmlText = '<div class="col-md-6"><input type="radio" name="'+ questionNum +'" /><label>' +
          randomQuestions[0].misDiscription + '</label></div>';

          if(rnd2 == 0){
            htmlText += ansDescriptionHtmlText;
            htmlText += misDiscriptionHtmlText;
          }else{
            htmlText += misDiscriptionHtmlText;
            htmlText += ansDescriptionHtmlText;
          }
        }

        htmlText += '</div>';

        $("#questionList").append(htmlText);
        randomQuestions.shift();
        questionNum += 1;
      }
    });
    // check box の css 付与
    $(function(){
      $('input').each(function(){
          var self = $(this),
            label = self.next(),
            label_text = label.text();

          label.remove();
          self.iCheck({
            checkboxClass: 'icheckbox_line-red',
            radioClass: 'iradio_line-red',
            insert: '<div class="icheck_line-icon"></div>' + label_text
          });
        });
      });

      //正誤チェック
      function calculateScore(){
        var score = 0;
        var totalQuestion = 0;
        $("[id^=ans-]").each(function(i, elem) {
          totalQuestion += 1;
          if($(elem).prop('checked')){
            score += 1;
          }
        });
        return score * 100 / totalQuestion;
      }

      //点数表示
      $("button").click(function(){
        var score =calculateScore();
        $("input").each(function(i, elem) {
          $(elem).attr("disabled", "disabled");
        });
        $("#answerCheck").html("");

        var scoreHtmlText = '<h1 style="text-align: center; color: #777;">あなたは<strong style="color: #8ACD35; font-size:3em;">' + score + '</strong>点です</h1><h3 style="color: #777;">';
        var message = "";
        if(score == 100){
          message = "完璧です！あなたはトレタマスターです。";
        }else if(score >= 80){
          message = "あと少し。わからなかった問題を復習しよう。";
        }else if (score >= 50) {
          message = "う〜ん。用語集全体を一通り眺めてみましょう。";
        }else if(score >= 30){
          message = "飲食店でアルバイトでもしてみては？";
        }else{
          message = "もしかして、ふざけてませんか？";
        }
        scoreHtmlText = scoreHtmlText + message + '</h3>';
        $("#showScore").html(scoreHtmlText);
      });

    </script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>